name = 'mbti-test-ca-ko-site'
type = 'javascript'
account_id = 'aad5c82543cd1f267b89737d0f56405e'
route = 'mbti-ko.ca.karrotmarket.com/*'
workers_dev = true

[build]
command = """
  yarn esbuild src/worker/site.js --bundle --outfile=workers-site/index.js --format=esm
"""

[build.upload]
format = 'service-worker'

[site]
bucket = './public'
entry-point = 'workers-site'
